<script setup>
import { computed, onMounted } from 'vue';
import { useMonitoring } from '../../composables/useMonitoring';

const props = defineProps({ baseUrl: { type: String, required: true } });
const { payload, loading, error, load, post } = useMonitoring(props.baseUrl);
const data = computed(() => payload.value?.data || { summary: {}, routers: { data: [] }, connections: { data: [] }, incidents: { data: [] } });
const list = (value) => value?.data || value || [];
const state = (value) => (value || 'unknown').toUpperCase();
onMounted(load);
</script>

<template>
    <div class="page-header"><div><p class="topbar__eyebrow">Network</p><h1>Monitoring</h1><p class="page-header__meta">Health observations and correlated incidents from Laravel.</p></div><span class="topbar__mode">SIMULATION MODE</span></div>
    <div v-if="error" class="alert alert-error" role="alert"><span class="alert__mark">!</span>{{ error }}</div>
    <div class="card monitoring-toolbar"><p><strong>Vue module foundation</strong> — business rules remain in Laravel.</p><button type="button" class="button--primary" :disabled="loading" @click="post('/api/v1/monitoring/check')">{{ loading ? 'Checking…' : 'Run Monitoring Check' }}</button></div>
    <div class="stat-grid"><article class="stat-card stat-card--accent"><div class="stat-card__label">Routers online</div><div class="stat-card__value">{{ data.summary.routers?.online || 0 }}</div></article><article class="stat-card stat-card--accent"><div class="stat-card__label">Connections online</div><div class="stat-card__value">{{ data.summary.connections?.online || 0 }}</div></article><article class="stat-card stat-card--warning"><div class="stat-card__label">Connections offline</div><div class="stat-card__value">{{ data.summary.connections?.offline || 0 }}</div></article><article class="stat-card stat-card--danger"><div class="stat-card__label">Active outages</div><div class="stat-card__value">{{ list(data.incidents).filter((incident) => ['detected', 'acknowledged'].includes(incident.status)).length }}</div></article></div>
    <div class="section-heading"><h2>Routers</h2></div><div class="table-scroll"><table><tr><th>Router</th><th>Health</th><th>Latency</th><th>Packet loss</th><th>Provider</th><th>Simulation</th></tr><tr v-for="router in list(data.routers)" :key="router.subject_id"><td>{{ router.name }}</td><td><span class="ui-status-badge" :class="`ui-status-badge--${router.health_state}`">{{ state(router.health_state) }}</span></td><td>{{ router.latency_ms ?? '—' }}{{ router.latency_ms !== null ? ' ms' : '' }}</td><td>{{ router.packet_loss_percent ?? '—' }}{{ router.packet_loss_percent !== null ? '%' : '' }}</td><td>{{ router.provider }}</td><td><button type="button" @click="post(`/api/v1/monitoring/routers/${router.subject_id}/simulation`, { state: router.health_state === 'offline' ? 'online' : 'offline' })">Set {{ router.health_state === 'offline' ? 'Online' : 'Offline' }}</button></td></tr></table></div>
    <div class="section-heading"><h2>Connections</h2></div><div class="table-scroll"><table><tr><th>Connection</th><th>Health</th><th>Customer</th><th>Router</th><th>Last observed</th><th>Lifecycle</th><th>Simulation</th></tr><tr v-for="connection in list(data.connections)" :key="connection.subject_id"><td>{{ connection.name }}</td><td><span class="ui-status-badge" :class="`ui-status-badge--${connection.health_state}`">{{ state(connection.health_state) }}</span></td><td>{{ connection.customer }}</td><td>{{ connection.router }}</td><td>{{ connection.observed_at }}</td><td>{{ connection.lifecycle_status }}</td><td><button type="button" @click="post(`/api/v1/monitoring/connections/${connection.subject_id}/simulation`, { state: connection.health_state === 'offline' ? 'online' : 'offline' })">Set {{ connection.health_state === 'offline' ? 'Online' : 'Offline' }}</button></td></tr></table></div>
    <div class="section-heading"><h2>Outage incidents</h2></div><div v-if="!list(data.incidents).length" class="empty-state">No correlated incidents.</div><div v-for="incident in list(data.incidents)" :key="incident.id" class="card incident-card"><strong>{{ state(incident.status) }}</strong> · {{ incident.router.name }} · {{ incident.affected_customers }} customers · {{ incident.affected_connections?.length || 0 }} connections <button v-if="incident.status === 'detected'" type="button" @click="post(`/api/v1/outages/${incident.id}/acknowledge`)">Acknowledge</button></div>
</template>