<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { useNetworkMap } from '../../composables/useNetworkMap.js';
import { customerMapStatus, mapBoundsFromPoints, mapHealthSummary, mapSettingEnabled, positionedMapPoints, routerMarkerDisplay, validCoordinatePair } from './networkMapUtils.js';
import { candidateCoordinate, candidateCount, cancelCandidates, createEditState, markCandidate, placementCandidate, placementMarkerClass, placementState, unlocatedResourceResults } from './networkMapEditUtils.js';
import NetworkMapDetailPanel from './NetworkMapDetailPanel.vue';

const ESRI_WORLD_IMAGERY_URL = 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}';
const ESRI_STREET_URL = 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png';
const ESRI_ATTRIBUTION = 'Tiles &copy; Esri';
const props = defineProps({ baseUrl: { type: String, default: '' }, workspace: { type: Boolean, default: false } });
const { state, load, saveResourceLocation } = useNetworkMap(props.baseUrl);
const mapEl = ref(null); const map = ref(null); const search = ref(''); const debouncedSearch = ref(''); const filter = ref('all'); const showLayers = ref(false); const showSettings = ref(false); const showRouters = ref(true); const showCustomers = ref(true); const basemap = ref('satellite'); const selectedRouter = ref(null); const selectedCustomer = ref(null); const currentZoom = ref(0); const locateMessage = ref(''); const saveMessage = ref(''); const editState = ref(createEditState()); const placement = ref(placementState()); const placementMarker = ref(null); const editError = ref(null); const now = ref(new Date());
const routerLayers = new Map(); const customerLayers = new Map(); let refreshTimer; let ageTimer;
const allRouters = computed(() => [...state.routers, ...state.unlocatedRouters]);
const routersWithCoordinates = computed(() => state.routers.filter(validCoordinatePair));
const customersWithCoordinates = computed(() => state.customers.filter(validCoordinatePair));
const settings = computed(() => state.settings ?? { default_latitude: null, default_longitude: null, default_zoom: 1.4, auto_fit: true, navigation_controls: true, show_attribution: true, show_router_name: true, show_status: true, show_telemetry: true });
const editEnabled = computed(() => editState.value.enabled); const unsavedCount = computed(() => candidateCount(editState.value));
const ageLabel = computed(() => state.lastUpdatedAt ? `${Math.max(0, Math.floor((now.value - state.lastUpdatedAt) / 1000))}s ago` : 'Waiting');
const routerStatus = (router) => (router.monitoring_state || 'unknown').toLowerCase(); const customerStatus = customerMapStatus;
const statusColor = (status) => ({ online: '#43e39a', degraded: '#e6b84b', offline: '#ef6666', isolated: '#ef6666', unknown: '#91a0ae' }[status] || '#91a0ae');
const filteredRouters = computed(() => filter.value === 'customer' ? [] : routersWithCoordinates.value.filter((router) => filter.value === 'all' || routerStatus(router) === filter.value));
const filteredCustomers = computed(() => filter.value === 'router' ? [] : customersWithCoordinates.value.filter((customer) => filter.value === 'all' || filter.value === 'customer' || customerStatus(customer) === filter.value));
const results = computed(() => { const term = debouncedSearch.value.trim().toLowerCase(); if (!term) return []; return [...unlocatedResourceResults(state.unlocatedRouters, state.unlocatedCustomers, term), ...allRouters.value.filter((item) => `${item.name} ${item.status}`.toLowerCase().includes(term)).map((item) => ({ ...item, type: 'router' })), ...state.customers.filter((item) => `${item.name} ${item.code || ''} ${item.network_identity || ''} ${item.router || ''}`.toLowerCase().includes(term)).map((item) => ({ ...item, type: 'customer' }))].filter((item, index, items) => items.findIndex((candidate) => `${candidate.type}:${candidate.id}` === `${item.type}:${item.id}`) === index).slice(0, 8); });
const health = computed(() => mapHealthSummary(allRouters.value, state.customers));
const coordinate = (resource) => [Number(resource.latitude), Number(resource.longitude)];
const showMarkerLabel = () => currentZoom.value >= 13;
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
const icon = (kind, label, status, showLabel = true, showStatus = true) => L.divIcon({ className: `leaflet-network-marker leaflet-network-marker--${kind}`, html: `<span class="leaflet-network-marker__body">${showLabel ? `<span class="leaflet-network-marker__label">${escapeHtml(label)}</span>` : ''}${showStatus ? `<span class="leaflet-network-marker__status" style="--status:${statusColor(status)}"></span>` : ''}</span>`, iconSize: showLabel ? [180, 32] : [26, 26], iconAnchor: showLabel ? [90, 32] : [13, 13] });
const popup = (resource, type) => type === 'customer' ? `<div class="map-popup__eyebrow">CUSTOMER</div><strong>${escapeHtml(resource.name)}</strong><div class="map-popup__code">${escapeHtml(resource.code || 'Customer')}</div><div class="map-popup__status"><i class="map-popup__dot" style="--status:${statusColor(customerStatus(resource))}"></i>${customerStatus(resource).toUpperCase()}</div><div class="map-popup__facts"><span>${escapeHtml(resource.connection_mode || 'Connection')}</span><b>${escapeHtml(resource.network_identity || '—')}</b><span>Activity</span><b>${escapeHtml(resource.activity_state || '—')}</b></div><div class="map-popup__actions"><button class="map-popup__detail" data-resource="customer:${resource.id}">Details</button><a target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query=${resource.latitude},${resource.longitude}">Google Maps</a></div>` : `<div class="map-popup__eyebrow">ROUTER</div><strong>${escapeHtml(resource.name)}</strong><div class="map-popup__status"><i class="map-popup__dot" style="--status:${statusColor(routerStatus(resource))}"></i>${routerStatus(resource).toUpperCase()}</div><div class="map-popup__facts"><span>RouterOS</span><b>${escapeHtml(resource.routeros_version || '—')}</b><span>Board</span><b>${escapeHtml(resource.board_name || '—')}</b></div><div class="map-popup__actions"><button class="map-popup__detail" data-resource="router:${resource.id}">Details</button><a target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query=${resource.latitude},${resource.longitude}">Google Maps</a></div>`;
const clearPlacementMarker = () => { placementMarker.value?.remove(); placementMarker.value = null; };
const setPlacementCandidate = (event) => { if (!placement.value.active || !map.value) return; const candidate = candidateCoordinate(event.latlng); placement.value = placementCandidate(placement.value, null, candidate); const placementIcon = L.divIcon({ className: placementMarkerClass(), html: '<span aria-hidden="true"></span>', iconSize: [28, 28], iconAnchor: [14, 14] }); if (!placementMarker.value) { placementMarker.value = L.marker([candidate.latitude, candidate.longitude], { draggable: true, icon: placementIcon }).addTo(map.value); placementMarker.value.on('dragend', () => { placement.value = placementCandidate(placement.value, null, candidateCoordinate(placementMarker.value.getLatLng())); }); } else { placementMarker.value.setLatLng([candidate.latitude, candidate.longitude]); } };
const beginPlacement = (resource, type) => { placement.value = placementCandidate(placementState(), { type, id: resource.id, name: resource.name }); selectedRouter.value = type === 'router' ? resource : null; selectedCustomer.value = type === 'customer' ? resource : null; clearPlacementMarker(); };
const select = (resource, type, fly = true) => { selectedRouter.value = type === 'router' ? resource : null; selectedCustomer.value = type === 'customer' ? resource : null; if (!validCoordinatePair(resource)) { beginPlacement(resource, type); return; } if (fly && map.value) map.value.flyTo(coordinate(resource), Math.max(map.value.getZoom(), 15), { duration: .5 }); };
const attachPopup = (marker, resource, type) => { marker.bindPopup(popup(resource, type), { className: 'cosmic-map-popup', maxWidth: 240 }); marker.bindTooltip(type === 'customer' ? `<strong>${escapeHtml(resource.name)}</strong><br><span>${escapeHtml(resource.network_identity || 'Customer')}</span>` : `<strong>${escapeHtml(resource.name)}</strong><br><span>${routerStatus(resource).toUpperCase()}</span>`, { className: 'cosmic-map-tooltip', direction: 'top', offset: [0, -10], opacity: .96 }); marker.on('popupopen', (event) => event.popup.getElement()?.querySelector('.map-popup__detail')?.addEventListener('click', () => select(resource, type, false))); };
const markDragged = (type, resource, marker) => { const current = editState.value.candidates.get(`${type}:${resource.id}`); editState.value = markCandidate(editState.value, type, resource.id, current?.original || { latitude: Number(resource.latitude), longitude: Number(resource.longitude) }, candidateCoordinate(marker.getLatLng())); };
const syncLayers = () => { if (!map.value) return; const sync = (items, layers, type, visible) => { const ids = new Set(items.map((item) => item.id)); layers.forEach((layer, id) => { if (!ids.has(id) || !visible) { layer.remove(); if (!visible) layers.delete(id); } }); if (!visible) return; items.forEach((resource) => { const markerSettings = type === 'router' ? routerMarkerDisplay(settings.value) : { showName: showMarkerLabel(), showStatus: mapSettingEnabled(settings.value, 'show_status') }; let marker = layers.get(resource.id); if (!marker) { marker = L.marker(coordinate(resource), { icon: icon(type, resource.name, type === 'router' ? routerStatus(resource) : customerStatus(resource), markerSettings.showName && showMarkerLabel(), markerSettings.showStatus), draggable: true }).on('dragend', () => markDragged(type, resource, marker)).on('click', () => select(resource, type, false)); attachPopup(marker, resource, type); marker.addTo(map.value); layers.set(resource.id, marker); } else { marker.setLatLng(coordinate(resource)); marker.setIcon(icon(type, resource.name, type === 'router' ? routerStatus(resource) : customerStatus(resource), markerSettings.showName && showMarkerLabel(), markerSettings.showStatus)); } if (editEnabled.value) marker.dragging.enable(); else marker.dragging.disable(); }); }; sync(filteredRouters.value, routerLayers, 'router', showRouters.value); sync(filteredCustomers.value, customerLayers, 'customer', showCustomers.value); };
const fitInfrastructure = () => { const points = positionedMapPoints(routersWithCoordinates.value, customersWithCoordinates.value); if (!map.value || !points.length) return; if (points.length === 1) map.value.setView(points[0], 15); else { const bounds = mapBoundsFromPoints(points); map.value.fitBounds([[bounds.south, bounds.west], [bounds.north, bounds.east]], { padding: [100, 100], maxZoom: 15 }); } };
const focusResult = (item) => { search.value = item.name; debouncedSearch.value = item.name; select(item, item.type); }; const locateMe = () => { locateMessage.value = ''; if (!navigator.geolocation) { locateMessage.value = 'Location is not available in this browser.'; return; } navigator.geolocation.getCurrentPosition(({ coords }) => map.value?.flyTo([coords.latitude, coords.longitude], 16), () => { locateMessage.value = 'Location permission was denied.'; }, { enableHighAccuracy: false, timeout: 8000 }); };
const togglePanel = (panel) => { showLayers.value = panel === 'layers' ? !showLayers.value : false; showSettings.value = panel === 'settings' ? !showSettings.value : false; };
const toggleEdit = () => { editError.value = null; saveMessage.value = ''; togglePanel(null); if (!editEnabled.value) { selectedRouter.value = null; selectedCustomer.value = null; } editState.value = editEnabled.value ? cancelCandidates(editState.value) : { ...editState.value, enabled: true }; syncLayers(); };
const cancelEdit = () => { editState.value.candidates.forEach((item) => (item.resourceType === 'customer' ? customerLayers : routerLayers).get(item.id)?.setLatLng([item.original.latitude, item.original.longitude])); editState.value = cancelCandidates(editState.value); editError.value = null; syncLayers(); };
const saveChanges = async () => { editError.value = null; saveMessage.value = ''; try { for (const item of editState.value.candidates.values()) await saveResourceLocation(item.resourceType, item.id, item.candidate.latitude, item.candidate.longitude); editState.value = createEditState(); await load(); syncLayers(); saveMessage.value = 'Map position saved'; window.setTimeout(() => { saveMessage.value = ''; }, 2600); } catch (error) { editError.value = error.message || 'Unable to save map changes.'; } };
const savePlacement = async () => { if (!placement.value.resource || !placement.value.candidate) return; await saveResourceLocation(placement.value.resource.type, placement.value.resource.id, placement.value.candidate.latitude, placement.value.candidate.longitude); placement.value = placementState(); clearPlacementMarker(); await load(); syncLayers(); };
const cancelPlacement = () => { placement.value = placementState(); clearPlacementMarker(); };
const setBasemap = () => { if (!map.value) return; map.value.eachLayer((layer) => { if (layer.options?.isCosmicBasemap) map.value.removeLayer(layer); }); L.tileLayer(basemap.value === 'satellite' ? ESRI_WORLD_IMAGERY_URL : ESRI_STREET_URL, { attribution: settings.value.show_attribution !== false ? (basemap.value === 'satellite' ? ESRI_ATTRIBUTION : '&copy; OpenStreetMap') : '', maxZoom: 19, isCosmicBasemap: true }).addTo(map.value).bringToBack(); };
let searchTimer;
watch(search, (value) => { clearTimeout(searchTimer); searchTimer = setTimeout(() => { debouncedSearch.value = value; }, 220); });
onMounted(async () => { await load(); const center = settings.value.default_latitude !== null ? [settings.value.default_latitude, settings.value.default_longitude] : [0, 20]; map.value = L.map(mapEl.value, { zoomControl: false, attributionControl: settings.value.show_attribution !== false }).setView(center, settings.value.default_zoom ?? 1.4); currentZoom.value = map.value.getZoom(); map.value.on('click', setPlacementCandidate); map.value.on('zoomend', () => { currentZoom.value = map.value.getZoom(); syncLayers(); }); if (mapSettingEnabled(settings.value, 'navigation_controls')) L.control.zoom({ position: 'bottomright' }).addTo(map.value); setBasemap(); map.value.whenReady(() => { syncLayers(); requestAnimationFrame(() => { map.value.invalidateSize(); if (settings.value.auto_fit !== false) fitInfrastructure(); }); }); refreshTimer = window.setInterval(() => load({ preserveError: true }), 16000); ageTimer = window.setInterval(() => { now.value = new Date(); }, 1000); });
watch([filteredRouters, filteredCustomers, showRouters, showCustomers, editEnabled], async () => { await nextTick(); syncLayers(); }, { deep: true }); watch(basemap, setBasemap); onBeforeUnmount(() => { clearTimeout(searchTimer); if (refreshTimer) clearInterval(refreshTimer); if (ageTimer) clearInterval(ageTimer); clearPlacementMarker(); map.value?.remove(); });
</script>

<template>
    <section class="gis-map-section" :class="{ 'gis-map-section--workspace': workspace }" aria-labelledby="gis-map-heading">
        <div v-if="!workspace" class="panel__head gis-map-section__head"><div><p class="panel__kicker">[GIS] Physical network infrastructure</p><h2 class="panel__title" id="gis-map-heading">GIS Network Map</h2></div><div class="panel__actions"><button class="button button--quiet button--sm" @click="fitInfrastructure">Fit infrastructure</button><button class="button button--quiet button--sm" :class="{ 'button--primary': editEnabled }" @click="toggleEdit">{{ editEnabled ? '✓ Editing' : 'Edit Map' }}</button></div></div>
        <div class="gis-map-layout" :class="{ 'gis-map-layout--workspace': workspace }"><div class="gis-map-canvas-wrap"><div ref="mapEl" class="gis-map-canvas gis-map-canvas--leaflet"></div>
            <div v-if="workspace" class="gis-workspace-topbar"><div><strong>GIS Network Map</strong><span>Physical network operations</span></div><div><span :class="state.stale ? 'gis-live gis-live--stale' : 'gis-live'">● {{ state.stale ? 'STALE' : 'LIVE' }}</span><span>Updated {{ ageLabel }}</span><button @click="fitInfrastructure">Fit</button><button :class="{ active: editEnabled }" @click="toggleEdit">{{ editEnabled ? '✓ Editing' : 'Edit Map' }}</button></div></div>
            <div v-if="workspace" class="gis-float gis-float--search"><div class="gis-search"><span aria-hidden="true">⌕</span><input v-model="search" aria-label="Search customer, router, IP" placeholder="Search customer, router, IP..." autocomplete="off"><button v-if="search" class="gis-search__clear" aria-label="Clear search" @click="search = ''; debouncedSearch = ''">×</button><span class="gis-search__shortcut">/</span></div><div v-if="results.length" class="gis-search-results"><button v-for="item in results" :key="`${item.type}:${item.id}`" @click="focusResult(item)"><span><b>{{ item.name }}</b><small>{{ item.type === 'router' ? `Router · ${routerStatus(item).toUpperCase()}` : `Customer · ${item.network_identity || '—'}` }}</small></span><span>›</span></button></div><div class="gis-filter-row"><button v-for="item in [['all','Semua'],['online','Online'],['isolated','Isolir'],['customer','Customer']]" :key="item[0]" :class="{ active: filter === item[0] }" @click="filter = item[0]">{{ item[1] }}</button></div></div>
            <div v-if="workspace" class="gis-float gis-health"><div class="gis-float__title">NETWORK HEALTH <span :class="state.stale ? 'gis-live gis-live--stale' : 'gis-live'">● {{ state.stale ? 'STALE' : 'LIVE' }}</span></div><div class="gis-health__grid"><span>Routers online <b>{{ health.routersOnline }}</b></span><span>Customers online <b>{{ health.customersOnline }}</b></span><span>Warning / isolated <b>{{ health.warning + health.isolated }}</b></span><span>Offline / unknown <b>{{ health.offline + health.unknown }}</b></span></div><small>Mapped customers only · Updated {{ ageLabel }}</small></div>
            <div v-if="workspace" class="gis-float gis-toolbar"><button title="Reset view" aria-label="Reset view" @click="fitInfrastructure">⌂</button><button title="Locate me" aria-label="Locate me" @click="locateMe">◎</button><button title="Layers" aria-label="Layers" :class="{ active: showLayers }" @click="togglePanel('layers')">▧</button><button title="Edit Map" aria-label="Edit Map" :class="{ active: editEnabled }" @click="toggleEdit">✎</button><button title="Settings" aria-label="Settings" @click="togglePanel('settings')">⚙</button></div>
            <div v-if="showLayers" class="gis-float gis-layers"><strong>LAYERS</strong><em>BASEMAP</em><label><input v-model="basemap" type="radio" value="satellite"> Satellite</label><label><input v-model="basemap" type="radio" value="street"> Street</label><em>RESOURCES</em><label><input v-model="showRouters" type="checkbox"> Routers</label><label><input v-model="showCustomers" type="checkbox"> Customers</label></div><a v-if="showSettings" class="gis-float gis-settings-link" href="/settings/gis-network-map">Open GIS settings →</a>
            <div v-if="editEnabled" class="gis-map-edit-toolbar" role="region" aria-label="Edit map actions" @pointerdown.stop @mousedown.stop @click.stop @dblclick.stop><div class="gis-map-edit-toolbar__copy"><strong>EDITING MAP</strong><span>Drag Router or Customer markers · {{ unsavedCount }} unsaved change{{ unsavedCount === 1 ? '' : 's' }}</span></div><small v-if="editError" class="field-error">{{ editError }}</small><div class="panel__actions"><button class="button button--quiet button--sm" type="button" @pointerdown.stop @click.stop="cancelEdit">Cancel</button><button class="button button--primary button--sm" type="button" :disabled="!unsavedCount || state.saving" @pointerdown.stop @click.stop="saveChanges">{{ state.saving ? 'Saving…' : 'Save Changes' }}</button></div></div>
            <div v-if="saveMessage" class="gis-save-message" role="status">{{ saveMessage }}</div>
            <div v-if="workspace" class="gis-float gis-legend"><strong>LEGEND</strong><span><i class="legend-dot legend-dot--router"></i>ROUTER</span><span><i class="legend-dot legend-dot--customer"></i>CUSTOMER</span><span><i class="legend-dot legend-dot--online"></i>ONLINE</span><span><i class="legend-dot legend-dot--warning"></i>WARNING</span><span><i class="legend-dot legend-dot--offline"></i>OFFLINE / ISOLATED</span><span><i class="legend-dot legend-dot--unknown"></i>UNKNOWN</span></div>
            <div v-if="state.loading && !state.lastUpdatedAt" class="gis-map-overlay"><p class="empty-state">Loading GIS Network Map…</p></div><div v-else-if="state.error && !state.lastUpdatedAt" class="gis-map-overlay"><p class="empty-state">{{ state.error }}</p></div>
        </div><NetworkMapDetailPanel v-if="!workspace || selectedRouter || selectedCustomer" :router="selectedRouter" :customer="selectedCustomer" :candidate="placement.candidate" :location-mode="placement.active" :saving="state.saving" :show-telemetry="settings.show_telemetry !== false" @close="selectedRouter = null; selectedCustomer = null; cancelPlacement()" @set-location="beginPlacement(selectedCustomer || selectedRouter, selectedCustomer ? 'customer' : 'router')" @cancel-location="cancelPlacement" @save-location="savePlacement" /></div>
    </section>
</template>