@extends('layouts.app')
@section('content')
<div class="page-header"><div><p class="eyebrow">[AGENT] · Network</p><h1>{{ $agent->name }}</h1><p class="page-header__meta">{{ $agent->identifier }}</p></div><div class="page-header__aside"><span class="ui-status-badge">[AGENT] {{ $health }}</span><span class="topbar__mode">{{ $compatibility }}</span></div></div>
<section class="panel"><div class="panel__head"><div><p class="panel__kicker">Operational identity</p><h2 class="panel__title">Heartbeat</h2></div></div><div class="panel__body"><dl class="definition-list"><dt>Last seen</dt><dd>{{ $agent->last_seen_at?->toDateTimeString() ?? 'Never' }}</dd><dt>Version</dt><dd class="mono-value">{{ $agent->version ?? '—' }}</dd><dt>Go runtime</dt><dd class="mono-value">{{ $agent->metadata['go_runtime'] ?? '—' }}</dd><dt>Platform</dt><dd class="mono-value">{{ ($agent->metadata['os'] ?? '').' '.($agent->metadata['architecture'] ?? '') }}</dd><dt>Uptime (s)</dt><dd class="mono-value">{{ $agent->metadata['uptime_seconds'] ?? '—' }}</dd><dt>Capabilities</dt><dd class="mono-value">{{ implode(', ', $agent->capabilities ?? []) }}</dd></dl></div></section>
@if($currentJob)<section class="panel"><div class="panel__head"><div><p class="panel__kicker">Current job</p><h2 class="panel__title">[JOB] RUNNING</h2></div></div><div class="panel__body"><dl class="definition-list"><dt>ID</dt><dd>{{ $currentJob->id }}</dd><dt>Attempt</dt><dd>{{ $currentJob->attempt }}</dd><dt>Lease expires</dt><dd>{{ $currentJob->lease_expires_at?->toDateTimeString() ?? '—' }}</dd><dt>Progress at</dt><dd>{{ $currentJob->last_progress_at?->toDateTimeString() ?? '—' }}</dd></dl></div></section>@endif
<section class="panel"><div class="panel__head"><div><p class="panel__kicker">Job counts</p><h2 class="panel__title">Recent work</h2></div></div><div class="panel__body"><div class="stat-row">@foreach(['PENDING','RUNNING','SUCCEEDED','FAILED'] as $label)<div class="stat"><span class="stat__label">[JOB] {{ $label }}</span><span class="stat__value">{{ $jobCounts[$label] ?? 0 }}</span></div>@endforeach</div><div class="table-scroll"><table><thead><tr><th>ID</th><th>Router</th><th>Status</th><th>Attempt</th><th>Failure code</th></tr></thead><tbody>@forelse($jobs as $job)<tr><td class="mono-value">{{ $job->id }}</td><td>{{ $job->router->name }}</td><td><span class="ui-status-badge">{{ $job->status }}</span></td><td>{{ $job->attempt }}</td><td class="mono-value">{{ $job->error_code ? '[WARN] '.$job->error_code : '—' }}</td></tr>@empty<tr><td colspan="5"><p class="empty-state">No jobs yet.</p></td></tr>@endforelse</tbody></table></div></div></section>
<section class="panel"><div class="panel__head"><div><p class="panel__kicker">Transition history</p><h2 class="panel__title">Bounded events</h2></div></div><div class="panel__body panel__body--flush"><div class="table-scroll"><table><thead><tr><th>Time</th><th>Type</th><th>Job</th><th>Attempt</th><th>Code</th></tr></thead><tbody>@forelse($events as $event)<tr><td class="mono-value">{{ \Carbon\Carbon::parse($event->created_at)->toDateTimeString() }}</td><td>{{ $event->type }}</td><td class="mono-value">{{ $event->network_agent_job_id ?? '—' }}</td><td>{{ $event->attempt ?? '—' }}</td><td class="mono-value">{{ $event->code ? '[WARN] '.$event->code : '—' }}</td></tr>@empty<tr><td colspan="5"><p class="empty-state">No events.</p></td></tr>@endforelse</tbody></table></div></div></section>
<section class="panel"><div class="panel__head"><h2 class="panel__title">Attempt history</h2></div><div class="panel__body"><div class="table-scroll"><table><thead><tr><th>Job / attempt</th><th>Status</th><th>Claimed</th><th>Progress</th><th>Lease expires</th><th>Completed</th><th>Duration (s)</th><th>Failure</th></tr></thead><tbody>@foreach($attempts as $attempt)<tr><td>{{ $attempt->network_agent_job_id }} / {{ $attempt->attempt }}</td><td>{{ $attempt->status }}</td><td>{{ $attempt->claimed_at }}</td><td>{{ $attempt->last_progress_at }}</td><td>{{ $attempt->lease_expires_at }}</td><td>{{ $attempt->completed_at ?? '-' }}</td><td>{{ max(0, (int) \Carbon\Carbon::parse($attempt->claimed_at)->diffInSeconds($attempt->completed_at ? \Carbon\Carbon::parse($attempt->completed_at) : now())) }}</td><td>{{ $attempt->failure_code ?? '-' }}</td></tr>@endforeach</tbody></table></div></div></section>
<section class="panel"><div class="panel__head"><h2 class="panel__title">Job lifecycle timestamps</h2></div><div class="panel__body"><div class="table-scroll"><table><thead><tr><th>Job</th><th>Created</th><th>Claimed</th><th>Progress</th><th>Completed</th><th>Safe diagnostic</th></tr></thead><tbody>@foreach($jobs as $job)<tr><td>{{ $job->id }}</td><td>{{ $job->created_at?->toDateTimeString() }}</td><td>{{ $job->claimed_at?->toDateTimeString() ?? '-' }}</td><td>{{ $job->last_progress_at?->toDateTimeString() ?? '-' }}</td><td>{{ $job->completed_at?->toDateTimeString() ?? '-' }}</td><td>{{ $job->error_code ?? '-' }} {{ $job->error_message ?? '' }}</td></tr>@endforeach</tbody></table></div></div></section>
@endsection
